In [1]:
# Import Dependencies
import os
import csv
import pandas as pd
from sqlalchemy import create_engine

In [5]:
# load and store dfs
citibike_2022_df = pd.concat(
    map(pd.read_csv, [
        'Resources/2022-data/JC-202201-citibike-tripdata.csv',
        'Resources/2022-data/JC-202202-citibike-tripdata.csv',
        'Resources/2022-data/JC-202203-citibike-tripdata.csv',
        'Resources/2022-data/JC-202204-citibike-tripdata.csv',
        'Resources/2022-data/JC-202205-citibike-tripdata.csv',
        'Resources/2022-data/JC-202206-citibike-tripdata.csv',
        'Resources/2022-data/JC-202207-citbike-tripdata.csv',
        'Resources/2022-data/JC-202208-citibike-tripdata.csv',
        'Resources/2022-data/JC-202209-citibike-tripdata.csv',
        'Resources/2022-data/JC-202210-citibike-tripdata.csv',
        'Resources/2022-data/JC-202211-citibike-tripdata.csv',
        'Resources/2022-data/JC-202212-citibike-tripdata.csv'
        ]), ignore_index=True)

output_data_2022 = "./Resources/citibike_2022.csv"

citibike_2022_df.info()
citibike_2022_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 895485 entries, 0 to 895484
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             895485 non-null  object
 1   rideable_type       895485 non-null  object
 2   started_at          895485 non-null  object
 3   ended_at            895485 non-null  object
 4   start_station_name  895475 non-null  object
 5   start_station_id    895475 non-null  object
 6   end_station_name    892281 non-null  object
 7   end_station_id      892281 non-null  object
 8   start_lat           895485 non-null  float64
 9   start_lng           895485 non-null  float64
 10  end_lat             893515 non-null  float64
 11  end_lng             893515 non-null  float64
 12  member_casual       895485 non-null  object
dtypes: float64(4), object(9)
memory usage: 88.8+ MB

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,CA5837152804D4B5,electric_bike,2022-01-26 18:50:39,2022-01-26 18:51:53,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
1,BA06A5E45B6601D2,classic_bike,2022-01-28 13:14:07,2022-01-28 13:20:23,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,member
2,7B6827D7B9508D93,classic_bike,2022-01-10 19:55:13,2022-01-10 20:00:37,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,member
3,6E5864EA6FCEC90D,electric_bike,2022-01-26 07:54:57,2022-01-26 07:55:22,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
4,E24954255BBDE32D,electric_bike,2022-01-13 18:44:46,2022-01-13 18:45:43,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
895480,D438F1622839AC50,classic_bike,2022-12-06 15:43:38,2022-12-06 15:53:57,Dey St,JC065,Riverview Park,JC057,40.737828,-74.067083,40.744319,-74.043991,member
895481,747A63A8E782D171,electric_bike,2022-12-08 08:17:51,2022-12-08 08:23:33,9 St HBLR - Jackson St & 8 St,HB305,City Hall - Washington St & 1 St,HB105,40.747907,-74.038412,40.737360,-74.030970,casual
895482,AE090858CFDE6E82,electric_bike,2022-12-23 14:10:07,2022-12-23 14:14:18,Mama Johnson Field - 4 St & Jackson St,HB404,City Hall - Washington St & 1 St,HB105,40.743140,-74.040041,40.737360,-74.030970,member
895483,B3CC8E70AF4E259C,classic_bike,2022-12-02 04:43:25,2022-12-02 04:46:55,Mama Johnson Field - 4 St & Jackson St,HB404,City Hall - Washington St & 1 St,HB105,40.743135,-74.040080,40.737360,-74.030970,member
895484,176B601F21327350,classic_bike,2022-12-30 14:50:17,2022-12-30 14:55:37,14 St Ferry - 14 St & Shipyard Ln,HB202,City Hall - Washington St & 1 St,HB105,40.752747,-74.024035,40.737360,-74.030970,member

In [6]:
# rename columns
citibike_2022_df = citibike_2022_df.rename(columns = {
    'ride_id': 'ride id',
    'rideable_type': 'ride type', 
    'started_at': 'start at', 
    'ended_at': 'end at',
    'start_station_name': 'start station name', 
    'start_station_id': 'start station id', 
    'end_station_name': 'end station name',
    'end_station_id': 'end station id', 
    'start_lat': 'start latitude', 
    'start_lng': 'start longitude', 
    'end_lat': 'end latitude', 
    'end_lng': 'end longitude',
    'member_casual': 'membership'
})
citibike_2022_df.head()

,ride id,ride type,start at,end at,start station name,start station id,end station name,end station id,start latitude,start longitude,end latitude,end longitude,membership
0,CA5837152804D4B5,electric_bike,2022-01-26 18:50:39,2022-01-26 18:51:53,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
1,BA06A5E45B6601D2,classic_bike,2022-01-28 13:14:07,2022-01-28 13:20:23,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,member
2,7B6827D7B9508D93,classic_bike,2022-01-10 19:55:13,2022-01-10 20:00:37,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,member
3,6E5864EA6FCEC90D,electric_bike,2022-01-26 07:54:57,2022-01-26 07:55:22,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
4,E24954255BBDE32D,electric_bike,2022-01-13 18:44:46,2022-01-13 18:45:43,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member

In [7]:
#export to csv
citibike_2022_df.to_csv("./Resources/citibike_2022.csv", index = False)

In [9]:
# load and store dfs
citibike_2023_df = pd.concat(
    map(pd.read_csv, [
        'Resources/2023-data/JC-202301-citibike-tripdata.csv',
        'Resources/2023-data/JC-202302-citibike-tripdata.csv',
        'Resources/2023-data/JC-202303-citibike-tripdata.csv',
        'Resources/2023-data/JC-202304-citibike-tripdata.csv',
        'Resources/2023-data/JC-202305-citibike-tripdata.csv',
        'Resources/2023-data/JC-202306-citibike-tripdata.csv',
        'Resources/2023-data/JC-202307-citibike-tripdata.csv',
        'Resources/2023-data/JC-202308-citibike-tripdata.csv',
        'Resources/2023-data/JC-202309-citibike-tripdata.csv',
        'Resources/2023-data/JC-202310-citibike-tripdata.csv',
        'Resources/2023-data/JC-202311-citibike-tripdata.csv',
        'Resources/2023-data/JC-202312-citibike-tripdata.csv'
        ]), ignore_index=True)
# output file path
output_data_2023 = "./Resources/citibike_2023.csv"
# #export to csv
# citibike_2021_df.to_csv("./Resources/citibike_2021.csv", index = False)

citibike_2023_df.info()
citibike_2023_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 988851 entries, 0 to 988850
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             988851 non-null  object
 1   rideable_type       988851 non-null  object
 2   started_at          988851 non-null  object
 3   ended_at            988851 non-null  object
 4   start_station_name  988766 non-null  object
 5   start_station_id    988766 non-null  object
 6   end_station_name    985532 non-null  object
 7   end_station_id      985532 non-null  object
 8   start_lat           988851 non-null  float64
 9   start_lng           988851 non-null  float64
 10  end_lat             987897 non-null  float64
 11  end_lng             987897 non-null  float64
 12  member_casual       988851 non-null  object
dtypes: float64(4), object(9)
memory usage: 98.1+ MB

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,0905B18B365C9D20,classic_bike,2023-01-28 09:18:10,2023-01-28 09:28:52,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Hamilton Park,JC009,40.735938,-74.030305,40.727596,-74.044247,member
1,B4F0562B05CB5404,electric_bike,2023-01-23 20:10:12,2023-01-23 20:18:27,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Southwest Park - Jackson St & Observer Hwy,HB401,40.735938,-74.030305,40.737551,-74.041664,member
2,5ABF032895F5D87E,classic_bike,2023-01-29 15:27:04,2023-01-29 15:32:38,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Marshall St & 2 St,HB408,40.735944,-74.030383,40.740802,-74.042521,member
3,E7E1F9C53976D2F9,classic_bike,2023-01-24 18:35:08,2023-01-24 18:42:13,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Hamilton Park,JC009,40.735986,-74.030364,40.727596,-74.044247,member
4,323165780CA0734B,classic_bike,2023-01-21 20:44:09,2023-01-21 20:48:08,Hamilton Park,JC009,Manila & 1st,JC082,40.727596,-74.044247,40.721651,-74.042884,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
988846,7E862701EE7A6A03,classic_bike,2023-12-20 17:55:41,2023-12-20 18:00:10,Heights Elevator,JC059,Bloomfield St & 15 St,HB203,40.748720,-74.040487,40.754530,-74.026580,casual
988847,DFAF91AB91BE25DB,classic_bike,2023-12-13 14:36:43,2023-12-13 14:42:31,Heights Elevator,JC059,Bloomfield St & 15 St,HB203,40.748767,-74.040470,40.754530,-74.026580,member
988848,AEE7B49E6EDFAE6F,classic_bike,2023-12-18 16:40:00,2023-12-18 16:45:45,6 St & Grand St,HB302,Bloomfield St & 15 St,HB203,40.744291,-74.034404,40.754530,-74.026580,member
988849,A38E98956AD72EFB,classic_bike,2023-12-02 13:42:51,2023-12-02 13:50:42,6 St & Grand St,HB302,Bloomfield St & 15 St,HB203,40.744398,-74.034501,40.754530,-74.026580,member
988850,F16E0B969D877368,classic_bike,2023-12-19 16:30:13,2023-12-19 16:36:54,6 St & Grand St,HB302,Clinton St & 7 St,HB303,40.744398,-74.034501,40.745420,-74.033320,member

In [10]:
citibike_2023_df = citibike_2023_df.rename(columns = {
    'ride_id': 'ride id',
    'rideable_type': 'ride type', 
    'started_at': 'start at', 
    'ended_at': 'end at',
    'start_station_name': 'start station name', 
    'start_station_id': 'start station id', 
    'end_station_name': 'end station name',
    'end_station_id': 'end station id', 
    'start_lat': 'start latitude', 
    'start_lng': 'start longitude', 
    'end_lat': 'end latitude', 
    'end_lng': 'end longitude',
    'member_casual': 'membership'
})
citibike_2023_df.head()

,ride id,ride type,start at,end at,start station name,start station id,end station name,end station id,start latitude,start longitude,end latitude,end longitude,membership
0,0905B18B365C9D20,classic_bike,2023-01-28 09:18:10,2023-01-28 09:28:52,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Hamilton Park,JC009,40.735938,-74.030305,40.727596,-74.044247,member
1,B4F0562B05CB5404,electric_bike,2023-01-23 20:10:12,2023-01-23 20:18:27,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Southwest Park - Jackson St & Observer Hwy,HB401,40.735938,-74.030305,40.737551,-74.041664,member
2,5ABF032895F5D87E,classic_bike,2023-01-29 15:27:04,2023-01-29 15:32:38,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Marshall St & 2 St,HB408,40.735944,-74.030383,40.740802,-74.042521,member
3,E7E1F9C53976D2F9,classic_bike,2023-01-24 18:35:08,2023-01-24 18:42:13,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Hamilton Park,JC009,40.735986,-74.030364,40.727596,-74.044247,member
4,323165780CA0734B,classic_bike,2023-01-21 20:44:09,2023-01-21 20:48:08,Hamilton Park,JC009,Manila & 1st,JC082,40.727596,-74.044247,40.721651,-74.042884,member

In [11]:
#export to csv
citibike_2023_df.to_csv("./Resources/citibike_2023.csv", index = False)

In [13]:
# combine 2022 and 2023 
citibike_combined_df = pd.concat(
    map(pd.read_csv, [
        './Resources/citibike_2022.csv',
        './Resources/citibike_2023.csv'
        ]), ignore_index=True)
# output file path
output_data_combined = "./Resources/citibike_combined.csv"

citibike_combined_df.info()
citibike_combined_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1884336 entries, 0 to 1884335
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride id             object
 1   ride type           object
 2   start at            object
 3   end at              object
 4   start station name  object
 5   start station id    object
 6   end station name    object
 7   end station id      object
 8   start latitude      float64
 9   start longitude     float64
 10  end latitude        float64
 11  end longitude       float64
 12  membership          object
dtypes: float64(4), object(9)
memory usage: 186.9+ MB

,ride id,ride type,start at,end at,start station name,start station id,end station name,end station id,start latitude,start longitude,end latitude,end longitude,membership
0,CA5837152804D4B5,electric_bike,2022-01-26 18:50:39,2022-01-26 18:51:53,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
1,BA06A5E45B6601D2,classic_bike,2022-01-28 13:14:07,2022-01-28 13:20:23,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,member
2,7B6827D7B9508D93,classic_bike,2022-01-10 19:55:13,2022-01-10 20:00:37,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,member
3,6E5864EA6FCEC90D,electric_bike,2022-01-26 07:54:57,2022-01-26 07:55:22,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
4,E24954255BBDE32D,electric_bike,2022-01-13 18:44:46,2022-01-13 18:45:43,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1884331,7E862701EE7A6A03,classic_bike,2023-12-20 17:55:41,2023-12-20 18:00:10,Heights Elevator,JC059,Bloomfield St & 15 St,HB203,40.748720,-74.040487,40.754530,-74.026580,casual
1884332,DFAF91AB91BE25DB,classic_bike,2023-12-13 14:36:43,2023-12-13 14:42:31,Heights Elevator,JC059,Bloomfield St & 15 St,HB203,40.748767,-74.040470,40.754530,-74.026580,member
1884333,AEE7B49E6EDFAE6F,classic_bike,2023-12-18 16:40:00,2023-12-18 16:45:45,6 St & Grand St,HB302,Bloomfield St & 15 St,HB203,40.744291,-74.034404,40.754530,-74.026580,member
1884334,A38E98956AD72EFB,classic_bike,2023-12-02 13:42:51,2023-12-02 13:50:42,6 St & Grand St,HB302,Bloomfield St & 15 St,HB203,40.744398,-74.034501,40.754530,-74.026580,member
1884335,F16E0B969D877368,classic_bike,2023-12-19 16:30:13,2023-12-19 16:36:54,6 St & Grand St,HB302,Clinton St & 7 St,HB303,40.744398,-74.034501,40.745420,-74.033320,member

In [14]:
#export to csv
citibike_combined_df.to_csv("./Resources/citibike_combined.csv", index = False)